language: node_js
sudo: required
node_js: stable
branches:
    only:
    - master
addons:
  chrome: stable
cache:
    apt: true
    directories:
        - back_end/node_modules
        - front_end_manage/node_modules
before_install:
    - cd front_end_manage
    - export TZ='Asia/Shanghai' # 更改时区
install:
    - npm install
script:
    - npm run unit
    - npm run build:prod
