const USERTYPE_OUTSCHOOL = 2;
const USERTYPE_STUDENT = 0;
const USERTYPE_TEACHER = 1;

exports.USERTYPE_OUTSCHOOL = USERTYPE_OUTSCHOOL;
exports.USERTYPE_STUDENT = USERTYPE_STUDENT;
exports.USERTYPE_TEACHER = USERTYPE_TEACHER;